### ISSUE TITLE
failing tests in src/bluehawk

### ISSUE THREAD

**Issue by masukomi** [mongodb-university/Bluehawk#149]
## expected behavior
no failing tests in fresh clone on `main` branch.

## actual behavior
tests fail in fresh clone on `main` branch.

## bug replication
1. clone repo
2. cd src/bluehawk
3. run `npm run test`
4. 😿

## user environment
npm version 9.7.1  
Note: not sure where that version is coming from. It appears to be defined in the repo somewhere because when I `cd`'d into it the root dir my system switched from my default version to 9.7.1
macOS Sonoma (14.2.1)
ARM architecture.

## output
I've attached a file with the raw test output and the ridiculously long screenshot of the same material (easier to read because colors) is below. 

[bluehawk_test_output.txt](https://github.com/mongodb-university/Bluehawk/files/13951558/bluehawk_test_output.txt)

![bluehawk_test_output](https://github.com/mongodb-university/Bluehawk/assets/2829/686e7a09-9990-44af-bb18-84009a55b8cf)

**Comment by masukomi** [comment]
note: re the arror that says `Unable to use "first char" lexer optimizations:` and complains about parsing a regexp.

I've added a note to [this regexp-to-ast issue](https://github.com/bd82/regexp-to-ast/issues/77). The problem has existed since at least 2020. `regexp-to-ast` is being brought in by the `chevrotain` library which is a direct dependency of Bluehawk. The current Version of `chevrotain` appears to have a fork of `regexp-to-ast` in it ([inner package here](https://github.com/Chevrotain/chevrotain/tree/4272462f2c88846357dc95dfdd5684d87c153c4f/packages/regexp-to-ast)) which might solve this.

**Comment by cbush** [comment]
Hi, thanks for raising. Please try with Node v20+ and let me know. Thanks!

**Comment by dacharyc** [comment]
Thanks for reporting this! I've updated some of the failing tests, including applying a workaround for the `Unable to use "first char" lexer optimizations:` issue, per the Chevrotain documentation.

It looks like any remaining failures are related to discrepancies in error reporting between different Node versions. I believe you can safely ignore those failures, or try with Node v21 and should see all the tests passing. I'm going to go ahead and close this issue.
